"""Initial schema

Revision ID: 4be5cb5a371f
Revises: 
Create Date: 2026-06-20 18:04:22.735071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4be5cb5a371f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_admin_users_id'), 'admin_users', ['id'], unique=False)
    op.create_table('districts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lgd_code', sa.String(length=10), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('centroid_lat', sa.Float(), nullable=True),
    sa.Column('centroid_lng', sa.Float(), nullable=True),
    sa.Column('geometry', sa.JSON(), nullable=True),
    sa.Column('is_seeded', sa.Boolean(), nullable=True),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.Column('open_defecation_pct', sa.Float(), nullable=True),
    sa.Column('elderly_child_pct', sa.Float(), nullable=True),
    sa.Column('hospital_density_per_100k', sa.Float(), nullable=True),
    sa.Column('river_danger_mark_m', sa.Float(), nullable=True),
    sa.Column('historical_flood_freq_per_decade', sa.Integer(), nullable=True),
    sa.Column('v_score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_districts_id'), 'districts', ['id'], unique=False)
    op.create_index(op.f('ix_districts_lgd_code'), 'districts', ['lgd_code'], unique=True)
    op.create_table('subscribers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('preferred_language', sa.String(length=5), nullable=True),
    sa.Column('threshold', sa.String(length=10), nullable=True),
    sa.Column('channels', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscribers_id'), 'subscribers', ['id'], unique=False)
    op.create_table('admin_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_user_id', sa.Integer(), nullable=True),
    sa.Column('district_id', sa.Integer(), nullable=True),
    sa.Column('disease', sa.String(length=50), nullable=True),
    sa.Column('case_count', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('reported_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['admin_user_id'], ['admin_users.id'], ),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_reports_id'), 'admin_reports', ['id'], unique=False)
    op.create_table('risk_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('district_id', sa.Integer(), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('w_score', sa.Integer(), nullable=True),
    sa.Column('e_score', sa.Integer(), nullable=True),
    sa.Column('v_score', sa.Integer(), nullable=True),
    sa.Column('r_score', sa.Integer(), nullable=True),
    sa.Column('zone', sa.String(length=10), nullable=True),
    sa.Column('is_replay', sa.Boolean(), nullable=True),
    sa.Column('replay_event', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_scores_computed_at'), 'risk_scores', ['computed_at'], unique=False)
    op.create_index(op.f('ix_risk_scores_district_id'), 'risk_scores', ['district_id'], unique=False)
    op.create_index(op.f('ix_risk_scores_id'), 'risk_scores', ['id'], unique=False)
    op.create_table('river_levels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('district_id', sa.Integer(), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.Column('level_m', sa.Float(), nullable=True),
    sa.Column('danger_mark_m', sa.Float(), nullable=True),
    sa.Column('exceedance_pct', sa.Float(), nullable=True),
    sa.Column('e_score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_river_levels_id'), 'river_levels', ['id'], unique=False)
    op.create_table('subscriber_districts',
    sa.Column('subscriber_id', sa.Integer(), nullable=False),
    sa.Column('district_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ),
    sa.ForeignKeyConstraint(['subscriber_id'], ['subscribers.id'], ),
    sa.PrimaryKeyConstraint('subscriber_id', 'district_id')
    )
    op.create_table('weather_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('district_id', sa.Integer(), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('rainfall_mm_24h', sa.Float(), nullable=True),
    sa.Column('humidity_pct', sa.Float(), nullable=True),
    sa.Column('temperature_c', sa.Float(), nullable=True),
    sa.Column('w_score', sa.Integer(), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weather_observations_id'), 'weather_observations', ['id'], unique=False)
    op.create_table('alerts_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subscriber_id', sa.Integer(), nullable=True),
    sa.Column('district_id', sa.Integer(), nullable=True),
    sa.Column('risk_score_id', sa.Integer(), nullable=True),
    sa.Column('channel', sa.String(length=10), nullable=True),
    sa.Column('dispatch_mode', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('message_body', sa.Text(), nullable=True),
    sa.Column('dispatched_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ),
    sa.ForeignKeyConstraint(['risk_score_id'], ['risk_scores.id'], ),
    sa.ForeignKeyConstraint(['subscriber_id'], ['subscribers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_log_id'), 'alerts_log', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alerts_log_id'), table_name='alerts_log')
    op.drop_table('alerts_log')
    op.drop_index(op.f('ix_weather_observations_id'), table_name='weather_observations')
    op.drop_table('weather_observations')
    op.drop_table('subscriber_districts')
    op.drop_index(op.f('ix_river_levels_id'), table_name='river_levels')
    op.drop_table('river_levels')
    op.drop_index(op.f('ix_risk_scores_id'), table_name='risk_scores')
    op.drop_index(op.f('ix_risk_scores_district_id'), table_name='risk_scores')
    op.drop_index(op.f('ix_risk_scores_computed_at'), table_name='risk_scores')
    op.drop_table('risk_scores')
    op.drop_index(op.f('ix_admin_reports_id'), table_name='admin_reports')
    op.drop_table('admin_reports')
    op.drop_index(op.f('ix_subscribers_id'), table_name='subscribers')
    op.drop_table('subscribers')
    op.drop_index(op.f('ix_districts_lgd_code'), table_name='districts')
    op.drop_index(op.f('ix_districts_id'), table_name='districts')
    op.drop_table('districts')
    op.drop_index(op.f('ix_admin_users_id'), table_name='admin_users')
    op.drop_table('admin_users')
    # ### end Alembic commands ###
